apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cdi-images-service-role
  namespace: cdi-images
  labels:
    app: cdi-images-app
rules:
- apiGroups: [""] 
  resources: ["dv"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdi-cloner
rules:
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["create"]
