= KubeVirt README
Antonio C. <antcosta (at) redhat (dot) com>
:icons: font
:toclevels: 3
:toc: left
:description: KubeVirt: READNE

== Introduction

This project is a logbook of the steps I took to execute different kubevirt 
 scenarios.

== Acronyms

CDI:: Containerized Data Importer (https://github.com/kubevirt/containerized-data-importer)
DV:: Data Volume (https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/)
NS:: Namespace
PV:: Kubernetes Persistent Volume
PVC:: Kubernetes Persistent Volume Claim
SC:: Kubernetes Storage Class
VM:: Virtual Machine
VMI:: Virtual Machine Instance

== Pre-requisites

* A Kubernetes cluster is already up and running 
** throughout this project a link:https://kind.sigs.k8s.io/[kind] cluster will be used.
* `virtctl` tool - check linkt:https://kubevirt.io/user-guide/operations/virtctl_client_tool/[kubevirt virtctl client tool]
* `jinja2`

== Install Kubevirt

Check the link:https://kubevirt.io/user-guide/operations/installation/[Kubevirt installation docs].

The version (`RELEASE`) used on this project: `v1.1.0`.


== Storage provisioning

For scenarios that require storage this project uses 
 [Rancher Local Path Provisioner](https://github.com/rancher/local-path-provisioner) as dynamic storage provisioner. 
 I wasn't able to put to work virtualization with a manual storage provisioner 
 model.

A new `local-path` storage class is created but the kind default `standard` SC is set as the _default_.

.Get a list of the Storage Classes
[source,bash]
----
kubectl get sc
----

.`standard` is marked as the `default` storage class
[source]
----
NAME                      PROVISIONER           
local-path                rancher.io/local-path 
standard (default)        rancher.io/local-path 
----

We'll need that the `local-pathstorage` SC is the default. For this we use 
 the following `kubectl` commands.

.Patch the storage classes so that the default `local-path`
[source,bash]
----
kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----

As a result the kind storage classes should be something like this.

[source,bash]
----
NAME                      PROVISIONER           
local-path (default)      rancher.io/local-path 
standard                  rancher.io/local-path 
----

== CDI

CDI installation and image loading is documented link:docs/cdi[here]


== Scenarios

* link:./docs/no-persistence/README.adoc[VM without Persistent Storage]
* link:./docs/persistence/README.adoc[VM with Persistent Storage]
* link:./docs/fedora/README.adoc[Fedora Cloud]
* link:./docs/windows/README.adoc[MS Windows VM]

== References

* https://kubevirt.io/2020/KubeVirt-VM-Image-Usage-Patterns.html
