apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 7Gi
  hostPath:
    path: /data/pv0002/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv0003/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  hostPath:
    path: /data/pv0004/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 7Gi
  hostPath:
    path: /data/pv0005/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0006
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv0006/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0007
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  hostPath:
    path: /data/pv0007/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0008
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv0008/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0009
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  hostPath:
    path: /data/pv0009/
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvstd0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pvstd0001/
  storageClassName: standard
