apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-fedora-cdi-role-binding
  namespace: cdi-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cdi-images-service-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: vm-fedora
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-cdi-cloner
  namespace: cdi-images
roleRef:
  kind: ClusterRole
  name: cdi-cloner
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: vm-fedora
